###
GET /api/v1/security/csrf-token
Host: localhost:9000
Accept: application/json


### Identity Requests



###
GET /api/v1/identities
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/identities/by-id?identityId=cf95f3b8-c8c6-41a2-9eee-7bd3b97aa6bb
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: qWZwQlCpygkHtsRTrRzwJbavZCNpqLmvWUSeDSmJeFQHwpF4mlBFIGLLrjsq0KJryDHER9SWSUJYmI2CbXb9OBy-HGQ286RM

{
    "authority": "ADMIN",
    "username": "burgasvv",
    "password": "burgasvv",
    "email": "burgasvv@gmail.com",
    "enabled": true
}

###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: -brBaIHvIAbh9d44iDnhcWgVYV9WHy-9HnyfA9lQbhdBLZfknYKlWLmMQTLMkOcPuxTVRFsjTD5nKkuQLRivYe1gVnZ0HaLc

{
    "authority": "USER",
    "username": "zagor",
    "password": "zagor",
    "email": "zagor@gmail.com",
    "enabled": true
}

###
PUT /api/v1/identities/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic zagor@gmail.com zagor
X-Csrf-Token: zCbmUJO2h5aC-eg8qY4WBsAvgIOVMKApie2tG9TZlXrOHDyEqB6CYKvV5qKvnNELmqMiM_MZreKkBcQEuomdeeDprRv7LAm8

{
    "id": "c8042d9d-7615-4111-b978-2e5cb51cdee2",
    "authority": "USER"
}

###
DELETE /api/v1/identities/delete?identityId=b40d51f1-1069-432e-b778-c753fa35495a
Host: localhost:9000
Accept: application/json

###
PUT /api/v1/identities/change-password?identityId=cf95f3b8-c8c6-41a2-9eee-7bd3b97aa6bb&newPassword=burgasvv
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv111
X-Csrf-Token: Hr15cImeaxADW6Y_I1vL5Yqe_uUnhKfUrWPAiuFHyI950vthL41MFr6vXnUuPZMIG3b_hOiv04cSs8X5y1H57IN-qe0dsJoF



### Category Requests



###
GET /api/v1/categories
Host: localhost:9000
Accept: application/json

###
GET /api/v1/categories/by-id?categoryId=fb76bfe2-f391-41ee-bb25-fc0b9fceb8f4
Host: localhost:9000
Accept: application/json

###
POST /api/v1/categories/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: drh0VcUvqfmsqwXzjRNyoJnRt0GTXAMnlGPmOg2hsbPy6PM5E9sQNvUWz8GBkzKVvz5Gk6DkmiPwaTcK9wDWCzyYgoHA35Ba

{
    "name": "Море-продукты",
    "description": "Описание категории Море-продукты"
}

###
PUT /api/v1/categories/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: drh0VcUvqfmsqwXzjRNyoJnRt0GTXAMnlGPmOg2hsbPy6PM5E9sQNvUWz8GBkzKVvz5Gk6DkmiPwaTcK9wDWCzyYgoHA35Ba

{
    "id": "4726fc8e-94ef-47c3-80e4-c987dfba7872",
    "name": "Море-продукты из Владивостока"
}

###
DELETE /api/v1/categories/delete?categoryId=4726fc8e-94ef-47c3-80e4-c987dfba7872
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: drh0VcUvqfmsqwXzjRNyoJnRt0GTXAMnlGPmOg2hsbPy6PM5E9sQNvUWz8GBkzKVvz5Gk6DkmiPwaTcK9wDWCzyYgoHA35Ba



### Product Requests



###
GET /api/v1/products
Host: localhost:9000
Accept: application/json

###
GET /api/v1/products/by-id?productId=422ac8f2-0241-4705-b4ca-74992b7fd3ae
Host: localhost:9000
Accept: application/json

###
POST /api/v1/products/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: Q_ShbAClMLaDAfgadUON7bbFE1CMfJCedLwSq2mbPBwoSx9hJ5XFCWPHBI6uOM8jRW65joHwPmm7S_KzF98gmVj4CCwQLi9V

{
    "categoryId": "fb76bfe2-f391-41ee-bb25-fc0b9fceb8f4",
    "name": "Домик в Деревне сметана",
    "description": "Описание продукта Домик в Деревне сметана",
    "price": 89.5
}

###
PUT /api/v1/products/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: zSv-DSRaxea5klA2pMfOUpQix_rqJ-QrOR5wSiKRGEyl2oVWqUqaaEc48d6Uq2cPlOr6MaMX6sPdEIYGWn1CeBPyLHydv7Vi

{
    "id": "3317404b-90e7-467d-87a0-0dd55c3adb86",
    "price": 98.8
}



### Store Requests



###
GET /api/v1/stores
Host: localhost:9000
Accept: application/json

###
GET /api/v1/stores/by-id?storeId=bc6239ba-20c2-4ffd-9053-869170ee0a4a
Host: localhost:9000
Accept: application/json

###
POST /api/v1/stores/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: Pu9DHo9_Dcio9NxlH-JHy50wZkXe3d17k4vbAfkdisDWQmn9XNxxLuxLaK2FwORTJ89zqq1USyfo7-pW97jqMZh-vPTgc1rN

{
    "name": "Магнит",
    "address": "Адрес магазина Магнит на Твардовского"
}



### Store Product Requests



###
POST /api/v1/store-product/add-products
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: geULRnlGrr6E1P_9Jo_NpU26mmNjGaSZ0bcP3oXJwDoGKm5huIEyfklzmN2p7ZyfQqL5kiyCt1sBLJK044Q57b2q8w4-SFlY

[
    {
        "storeId": "bc6239ba-20c2-4ffd-9053-869170ee0a4a",
        "productId": "422ac8f2-0241-4705-b4ca-74992b7fd3ae",
        "amount": 90
    },
    {
        "storeId": "bc6239ba-20c2-4ffd-9053-869170ee0a4a",
        "productId": "3317404b-90e7-467d-87a0-0dd55c3adb86",
        "amount": 80
    }
]

###
PUT /api/v1/store-product/change-amount
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: AqX28pxbcL7mHFNrl40xzRImpHC8Xv2r1fa_kqeI38B-cLngM8OSxahpQYzLemMOpqAF_SQXiUjYPcyGtpSH8Z_p7qMaQIrQ

{
    "storeId": "bc6239ba-20c2-4ffd-9053-869170ee0a4a",
    "productId": "3317404b-90e7-467d-87a0-0dd55c3adb86",
    "amount": 90
}

###
DELETE /api/v1/store-product/remove-products
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: SkqXz1jycw6xb4FQk1VELX0Ly_8tfu3tTe811NmIM1PleoDbfnul_GrCFzicXeRlonhwHU845scbGNrAKdcA5OzsBWPXT7Hs

[
    {
        "storeId": "bc6239ba-20c2-4ffd-9053-869170ee0a4a",
        "productId": "422ac8f2-0241-4705-b4ca-74992b7fd3ae"
    },
    {
        "storeId": "bc6239ba-20c2-4ffd-9053-869170ee0a4a",
        "productId": "3317404b-90e7-467d-87a0-0dd55c3adb86"
    }
]